import PlaceholderPreview from './PlaceholderPreview'
import CarBusinessComponentsPreview from './business/CarBusinessComponentsPreview'
import CarBubbleBusinessPreview from './business/car/CarBubbleBusinessPreview'
import CarHomeDefaultBusinessPreview from './business/car/CarHomeDefaultBusinessPreview'
import CarLocationInputBusinessPreview from './business/car/CarLocationInputBusinessPreview'
import CarPaymentBusinessPreview from './business/car/CarPaymentBusinessPreview'
import CarPaymentCompleteBusinessPreview from './business/car/CarPaymentCompleteBusinessPreview'
import CarPickupBusinessPreview from './business/car/CarPickupBusinessPreview'
import CarSendBusinessPreview from './business/car/CarSendBusinessPreview'
import CarWaitingBusinessPreview from './business/car/CarWaitingBusinessPreview'
import FlightBookingSuccessBusinessPreview from './business/flight/FlightBookingSuccessBusinessPreview'
import FlightBusinessComponentsPreview from './business/FlightBusinessComponentsPreview'
import FlightFormBusinessPreview from './business/flight/FlightFormBusinessPreview'
import FlightHomeBusinessPreview from './business/flight/FlightHomeBusinessPreview'
import FlightListBusinessPreview from './business/flight/FlightListBusinessPreview'
import FlightOrderDetailBusinessPreview from './business/flight/FlightOrderDetailBusinessPreview'
import FlightQuoteBusinessPreview from './business/flight/FlightQuoteBusinessPreview'
import HotelBookingSuccessBusinessPreview from './business/hotel/HotelBookingSuccessBusinessPreview'
import HotelBusinessComponentsPreview from './business/HotelBusinessComponentsPreview'
import HotelDetailBusinessPreview from './business/hotel/HotelDetailBusinessPreview'
import HotelFormBusinessPreview from './business/hotel/HotelFormBusinessPreview'
import HotelHomeBusinessBusinessPreview from './business/hotel/HotelHomeBusinessBusinessPreview'
import HotelListBusinessPreview from './business/hotel/HotelListBusinessPreview'
import HotelOrderDetailBusinessPreview from './business/hotel/HotelOrderDetailBusinessPreview'
import HotelRoomDetailBusinessPreview from './business/hotel/HotelRoomDetailBusinessPreview'
import PointsBusinessComponentsPreview from './business/PointsBusinessComponentsPreview'
import {
  GlobalColorPreview,
  GlobalIconPreview,
  GlobalLayoutPreview,
  GlobalRadiusPreview,
  GlobalShadowPreview,
  GlobalTypographyPreview,
} from './global-styles'
import {
  CommonBadgePreview,
  CommonBottomWatermarkPreview,
  CommonButtonPreview,
  CommonChevronActionPreview,
  CommonDividerPreview,
  CommonIPhoneBarPreview,
  CommonIPhoneFooterPreview,
  CommonMultiSelectPreview,
  CommonNavBarPreview,
  CommonPageBottomNavPreview,
  CommonPriceDisplayPreview,
  CommonSwitchPreview,
  CommonTagPreview,
} from './common/CommonComponentPreviews'
import CarHomeDefaultCasePreview from './page-cases/car/CarHomeDefaultCasePreview'
import CarBubbleCasePreview from './page-cases/car/CarBubbleCasePreview'
import CarLocationInputCasePreview from './page-cases/car/CarLocationInputCasePreview'
import CarPaymentCasePreview from './page-cases/car/CarPaymentCasePreview'
import CarPaymentCompleteCasePreview from './page-cases/car/CarPaymentCompleteCasePreview'
import CarSendCasePreview from './page-cases/car/CarSendCasePreview'
import CarPickupCasePreview from './page-cases/car/CarPickupCasePreview'
import CarWaitingCasePreview from './page-cases/car/CarWaitingCasePreview'
import FlightFormCasePreview from './page-cases/flight/FlightFormCasePreview'
import FlightBookingSuccessCasePreview from './page-cases/flight/FlightBookingSuccessCasePreview'
import FlightHomeCasePreview from './page-cases/flight/FlightHomeCasePreview'
import FlightListCasePreview from './page-cases/flight/FlightListCasePreview'
import FlightOrderDetailCasePreview from './page-cases/flight/FlightOrderDetailCasePreview'
import FlightQuoteCasePreview from './page-cases/flight/FlightQuoteCasePreview'
import HotelBookingSuccessCasePreview from './page-cases/hotel/HotelBookingSuccessCasePreview'
import HotelDetailCasePreview from './page-cases/hotel/HotelDetailCasePreview'
import HotelFormCasePreview from './page-cases/hotel/HotelFormCasePreview'
import HotelHomeBusinessCasePreview from './page-cases/hotel/HotelHomeBusinessCasePreview'
import HotelListCasePreview from './page-cases/hotel/HotelListCasePreview'
import HotelOrderDetailCasePreview from './page-cases/hotel/HotelOrderDetailCasePreview'
import HotelRoomDetailCasePreview from './page-cases/hotel/HotelRoomDetailCasePreview'
import PointsLuckyBagCasePreview from './page-cases/points/PointsLuckyBagCasePreview'
import PointsEarnTasksCasePreview from './page-cases/points/PointsEarnTasksCasePreview'
import PointsProductDetailOverlayCasePreview from './page-cases/points/PointsProductDetailOverlayCasePreview'
import PointsExchangeSuccessOverlayCasePreview from './page-cases/points/PointsExchangeSuccessOverlayCasePreview'
import PointsMallCasePreview from './page-cases/points/PointsMallCasePreview'

function createPlaceholderItem(config) {
  return function PlaceholderItem() {
    return <PlaceholderPreview {...config} />
  }
}

export const previewNavigation = [
  {
    id: 'group-global-style',
    label: '全局样式',
    type: 'group',
    children: [
      {
        id: 'global-style-color',
        label: '色彩规范',
        type: 'item',
        title: '色彩规范',
        pathLabel: '全局样式 / 色彩规范',
        description: '这里统一展示品牌主色、文字色阶和辅助背景色，方便页面和组件共用同一套色彩基准。',
        statusLabel: '已接入',
        maintenanceHint: '适合后续补充更多语义色、反馈色和业务线扩展色。',
        component: GlobalColorPreview,
      },
      {
        id: 'global-style-typography',
        label: '文字规范',
        type: 'item',
        title: '文字规范',
        pathLabel: '全局样式 / 文字规范',
        description: '这里统一展示页面标题、模块标题、正文和辅助说明的字号、行高与字重关系。',
        statusLabel: '已接入',
        maintenanceHint: '适合后续补充更多数字字重、英文场景和弱提示文字层级。',
        component: GlobalTypographyPreview,
      },
      {
        id: 'global-style-radius',
        label: '圆角规范',
        type: 'item',
        title: '圆角规范',
        pathLabel: '全局样式 / 圆角规范',
        description: '这里统一展示当前项目里常用的圆角等级，方便卡片、标签和胶囊组件保持一致。',
        statusLabel: '已接入',
        maintenanceHint: '适合后续补充特殊异形拼角和模块拼接规则。',
        component: GlobalRadiusPreview,
      },
      {
        id: 'global-style-shadow',
        label: '阴影规范',
        type: 'item',
        title: '阴影规范',
        pathLabel: '全局样式 / 阴影规范',
        description: '这里统一展示浮层卡片、激活态和轻悬停等几类最常用阴影层级。',
        statusLabel: '已接入',
        maintenanceHint: '适合后续补充深色背景下的阴影替代方案。',
        component: GlobalShadowPreview,
      },
      {
        id: 'global-style-layout',
        label: '布局规范',
        type: 'item',
        title: '布局规范',
        pathLabel: '全局样式 / 布局规范',
        description: '这里统一展示当前项目反复使用的基础间距节奏，方便页面编排与组件抽离时保持一致。',
        statusLabel: '已接入',
        maintenanceHint: '适合后续补充栅格、左右留白和吸底区域高度规范。',
        component: GlobalLayoutPreview,
      },
      {
        id: 'global-style-icon',
        label: '图标规范',
        type: 'item',
        title: '图标规范',
        pathLabel: '全局样式 / 图标规范',
        description: '这里统一展示图标导出时要遵守的正方形容器和尺寸基准，方便测量与替换。',
        statusLabel: '已接入',
        maintenanceHint: '适合后续补充描边风格、实心风格和不同业务线图标集。',
        component: GlobalIconPreview,
      },
    ],
  },
  {
    id: 'group-common',
    label: '通用组件',
    type: 'group',
    children: [
      {
        id: 'common-iphone-bar',
        label: '状态栏',
        type: 'item',
        title: '状态栏',
        pathLabel: '通用组件 / 状态栏',
        description: '统一维护移动端顶部状态栏组件，方便页面头图和常规页面共用。',
        statusLabel: '已接入',
        maintenanceHint: '适合后续补充深浅主题、特殊时间和状态组合。',
        component: CommonIPhoneBarPreview,
      },
      {
        id: 'common-iphone-footer',
        label: '底部指示条',
        type: 'item',
        title: '底部指示条',
        pathLabel: '通用组件 / 底部指示条',
        description: '统一维护页面底部的 iPhone 指示条组件，适合吸底操作区复用。',
        statusLabel: '已接入',
        maintenanceHint: '适合后续补充深浅底色适配。',
        component: CommonIPhoneFooterPreview,
      },
      {
        id: 'common-page-bottom-nav',
        label: '页面底部导航',
        type: 'item',
        title: '页面底部导航',
        pathLabel: '通用组件 / 页面底部导航',
        description: '统一维护一级页面底部导航组件，适合首页、行程、工作台等主入口页面复用。',
        statusLabel: '已接入',
        maintenanceHint: '适合后续补充更多激活态和不同业务线图标映射。',
        component: CommonPageBottomNavPreview,
      },
      {
        id: 'common-navbar',
        label: '导航栏',
        type: 'item',
        title: '导航栏',
        pathLabel: '通用组件 / 导航栏',
        description: '统一预留移动端导航栏的预览位，方便后续沉淀页面头部能力。',
        statusLabel: '可扩展',
        maintenanceHint: '适合后续沉淀返回、标题、操作按钮等。',
        component: CommonNavBarPreview,
      },
      {
        id: 'common-price-display',
        label: '价格',
        type: 'item',
        title: '价格',
        pathLabel: '通用组件 / 价格',
        description: '统一维护币种、金额、后缀和颜色层级，方便各业务页复用价格组件。',
        statusLabel: '已接入',
        maintenanceHint: '适合后续沉淀列表价、详情价、强调价等不同语义。',
        component: CommonPriceDisplayPreview,
      },
      {
        id: 'common-tag',
        label: '标签',
        type: 'item',
        title: '标签',
        pathLabel: '通用组件 / 标签',
        description: '统一维护轻量标签组件，适合筛选项、状态项、房型属性以及多选标签展示。',
        statusLabel: '已接入',
        maintenanceHint: '适合后续补充主次语义色、图标态和更多筛选交互变体。',
        component: CommonTagPreview,
      },
      {
        id: 'common-badge',
        label: '徽标',
        type: 'item',
        title: '徽标',
        pathLabel: '通用组件 / 徽标',
        description: '统一维护强调型徽标组件，适合因公、返现、状态提示等场景。',
        statusLabel: '已接入',
        maintenanceHint: '适合后续补充图标、描边和数字态。',
        component: CommonBadgePreview,
      },
      {
        id: 'common-divider',
        label: '分割线',
        type: 'item',
        title: '分割线',
        pathLabel: '通用组件 / 分割线',
        description: '统一维护横向和纵向分割线组件，适合卡片内部结构划分。',
        statusLabel: '已接入',
        maintenanceHint: '适合后续补充粗细、缩进和虚线样式。',
        component: CommonDividerPreview,
      },
      {
        id: 'common-bottom-watermark',
        label: '底部水印',
        type: 'item',
        title: '底部水印',
        pathLabel: '通用组件 / 底部水印',
        description: '统一维护页面底部弱感知品牌水印能力，当前区分酒店权益水印和首页规则水印两种场景。',
        statusLabel: '已接入',
        maintenanceHint: '适合后续补充更多业务线底部品牌文案和规则变体。',
        component: CommonBottomWatermarkPreview,
      },
      {
        id: 'common-chevron-action',
        label: '箭头动作',
        type: 'item',
        title: '箭头动作',
        pathLabel: '通用组件 / 箭头动作',
        description: '统一维护文字加箭头的轻交互组件，适合更多、收起和查看详情等场景。',
        statusLabel: '已接入',
        maintenanceHint: '适合后续补充左右上下方向和主次色。',
        component: CommonChevronActionPreview,
      },
      {
        id: 'common-button',
        label: '按钮',
        type: 'item',
        title: '按钮',
        pathLabel: '通用组件 / 按钮',
        description: '统一预留按钮类组件的预览位，后续可以直接接入真实按钮代码。',
        statusLabel: '可扩展',
        maintenanceHint: '适合后续沉淀主按钮、次按钮、禁用态等。',
        component: CommonButtonPreview,
      },
      {
        id: 'common-switch',
        label: '开关',
        type: 'item',
        title: '开关',
        pathLabel: '通用组件 / 开关',
        description: '统一预留开关类组件的预览位，后续可以逐步接入真实交互状态。',
        statusLabel: '可扩展',
        maintenanceHint: '适合后续沉淀默认态、选中态、禁用态。',
        component: CommonSwitchPreview,
      },
      {
        id: 'common-multi-select',
        label: '多选',
        type: 'item',
        title: '多选',
        pathLabel: '通用组件 / 多选',
        description: '统一维护多选框组件，适合条款确认、人员选择、筛选勾选等场景。',
        statusLabel: '已接入',
        maintenanceHint: '适合后续接入真实表单状态和批量选择交互。',
        component: CommonMultiSelectPreview,
      },
    ],
  },
  {
    id: 'group-business',
    label: '业务组件',
    type: 'group',
    children: [
      {
        id: 'business-hotel-components',
        label: '酒店',
        type: 'item',
        title: '酒店业务组件',
        pathLabel: '业务组件 / 酒店',
        description: '这里集中展示酒店业务下所有可复用组件，不再按酒店首页、列表页或详情页拆分目录。',
        statusLabel: '已接入',
        maintenanceHint: '按酒店业务统一维护，组件可被多个酒店页面案例复用。',
        component: HotelBusinessComponentsPreview,
      },
      {
        id: 'business-car-components',
        label: '用车',
        type: 'item',
        title: '用车业务组件',
        pathLabel: '业务组件 / 用车',
        description: '这里集中展示用车业务下所有可复用组件，不再按首页、等待接驾页或支付页拆分目录。',
        statusLabel: '已接入',
        maintenanceHint: '按用车业务统一维护，组件可被多个用车页面案例复用。',
        component: CarBusinessComponentsPreview,
      },
      {
        id: 'business-points-components',
        label: '积分权益',
        type: 'item',
        title: '积分权益业务组件',
        pathLabel: '业务组件 / 积分权益',
        description: '这里集中展示积分权益业务下所有可复用组件，当前接入小福包、积分商城相关模块。',
        statusLabel: '已接入',
        maintenanceHint: '按积分权益业务统一维护，后续积分、任务、权益模块直接归入这里。',
        component: PointsBusinessComponentsPreview,
      },
      {
        id: 'business-flight-components',
        label: '机票',
        type: 'item',
        title: '机票业务组件',
        pathLabel: '业务组件 / 机票',
        description: '这里集中展示机票业务下所有可复用组件，不再按首页、列表页或填单页拆分目录。',
        statusLabel: '已接入',
        maintenanceHint: '按机票业务统一维护，组件可被多个机票页面案例复用。',
        component: FlightBusinessComponentsPreview,
      },
      {
        id: 'business-train-components',
        label: '火车票',
        type: 'item',
        title: '火车票业务组件',
        pathLabel: '业务组件 / 火车票',
        description: '这里集中预留火车票业务组件目录，后续组件直接归入火车票业务下维护。',
        statusLabel: '待补充',
        maintenanceHint: '建议后续按车次信息、乘客信息和支付信息拆分。',
        component: createPlaceholderItem({
          badge: '业务组件',
          title: '火车票业务组件预留位',
          summary: '这里已经为火车票业务组件预留好了统一入口。',
          nextSteps: [
            '1. 新建火车票业务预览文件',
            '2. 注册到预览配置里',
            '3. 按统一结构维护',
          ],
        }),
      },
      {
        id: 'group-business-hotel',
        label: '酒店',
        hidden: true,
        type: 'group',
        statusLabel: '已接入',
        children: [
          {
            id: 'business-hotel-home-business',
            label: '酒店首页-因公',
            type: 'item',
            title: '酒店首页-因公组件预览',
            pathLabel: '业务组件 / 酒店 / 酒店首页-因公',
            description: '这里展示酒店首页-因公里拆出来的业务组件，适合按头部、填写卡片和底部权益模块持续维护。',
            statusLabel: '已接入',
            maintenanceHint: '当前挂载的是酒店首页-因公拆分后的业务组件。',
            component: HotelHomeBusinessBusinessPreview,
          },
          {
            id: 'business-hotel-list',
            label: '酒店列表页',
            type: 'item',
            title: '酒店列表页组件预览',
            pathLabel: '业务组件 / 酒店 / 酒店列表页',
            description: '这里展示酒店列表页里拆出来的业务组件，适合按搜索栏、筛选区和酒店卡片持续沉淀。',
            statusLabel: '已接入',
            maintenanceHint: '当前挂载的是酒店列表页拆分后的业务组件。',
            component: HotelListBusinessPreview,
          },
          {
            id: 'business-hotel-detail',
            label: '酒店详情页',
            type: 'item',
            title: '酒店详情页组件预览',
            pathLabel: '业务组件 / 酒店 / 酒店详情页',
            description: '这里展示酒店详情页里拆出来的业务组件，适合按头图、房型和酒店信息模块持续沉淀。',
            statusLabel: '已接入',
            maintenanceHint: '当前挂载的是酒店详情页拆分后的业务组件。',
            component: HotelDetailBusinessPreview,
          },
          {
            id: 'business-hotel-room-detail',
            label: '房型详情页',
            type: 'item',
            title: '房型详情页组件预览',
            pathLabel: '业务组件 / 酒店 / 房型详情页',
            description: '这里展示房型详情页里拆出来的业务组件，适合按卡片模块继续沉淀到酒店组件体系里。',
            statusLabel: '已接入',
            maintenanceHint: '当前挂载的是房型详情页拆分后的业务组件。',
            component: HotelRoomDetailBusinessPreview,
          },
          {
            id: 'business-hotel-form',
            label: '酒店填单页',
            type: 'item',
            title: '酒店填单页组件预览',
            pathLabel: '业务组件 / 酒店 / 酒店填单页',
            description: '这里展示酒店填单页里拆出来的业务组件，适合按模块核对和后续复用。',
            statusLabel: '已接入',
            maintenanceHint: '当前挂载的是酒店填单页拆分后的业务组件。',
            component: HotelFormBusinessPreview,
          },
          {
            id: 'business-hotel-booking-success',
            label: '酒店下单成功页',
            type: 'item',
            title: '酒店下单成功页组件预览',
            pathLabel: '业务组件 / 酒店 / 酒店下单成功页',
            description: '这里展示酒店下单成功页里拆出来的业务组件，适合按状态区、订单卡片和联订福利卡片继续维护。',
            statusLabel: '已接入',
            maintenanceHint: '当前挂载的是酒店下单成功页拆分后的业务组件。',
            component: HotelBookingSuccessBusinessPreview,
          },
          {
            id: 'business-hotel-order-detail',
            label: '酒店订单详情页',
            type: 'item',
            title: '酒店订单详情页组件预览',
            pathLabel: '业务组件 / 酒店 / 酒店订单详情页',
            description: '这里展示酒店订单详情页里拆出来的业务组件，适合按状态区、订单信息卡片和权益模块持续维护。',
            statusLabel: '已接入',
            maintenanceHint: '当前挂载的是酒店订单详情页拆分后的业务组件。',
            component: HotelOrderDetailBusinessPreview,
          },
        ],
      },
      {
        id: 'group-business-car',
        label: '用车',
        hidden: true,
        statusLabel: '已接入',
        type: 'group',
        children: [
          {
            id: 'business-car-home-default',
            label: '首页',
            type: 'item',
            title: '首页组件预览',
            pathLabel: '业务组件 / 用车 / 首页',
            description: '这里统一展示用车首页拆出来的业务组件，默认态和全态共用的组件与全态新增组件都会收口在这里维护。',
            statusLabel: '已接入',
            maintenanceHint: '当前挂载的是用车首页默认态与全态统一整理后的业务组件。',
            component: CarHomeDefaultBusinessPreview,
          },
          {
            id: 'business-car-location-input',
            label: '起终点输入页',
            type: 'item',
            title: '起终点输入页组件预览',
            pathLabel: '业务组件 / 用车 / 起终点输入页',
            description: '这里展示用车起终点输入页拆出来的地图背景、推荐上车点、悬浮按钮、输入卡片和安全指南卡。',
            statusLabel: '已接入',
            maintenanceHint: '当前挂载的是起终点输入页拆分后的业务组件。',
            component: CarLocationInputBusinessPreview,
          },
          {
            id: 'business-car-bubble',
            label: '冒泡页',
            type: 'item',
            title: '冒泡页组件预览',
            pathLabel: '业务组件 / 用车 / 冒泡页',
            description: '这里展示用车冒泡页拆出来的地图背景、路线信息、车型选择面板和底部呼叫区。',
            statusLabel: '已接入',
            maintenanceHint: '当前挂载的是用车冒泡页拆分后的业务组件。',
            component: CarBubbleBusinessPreview,
          },
          {
            id: 'business-car-waiting',
            label: '等待应答页',
            type: 'item',
            title: '等待应答页组件预览',
            pathLabel: '业务组件 / 用车 / 等待应答页',
            description: '这里展示用车等待应答页拆出来的顶部状态区、加速权益卡和追加更快车型卡。',
            statusLabel: '已接入',
            maintenanceHint: '当前挂载的是用车等待应答页拆分后的业务组件。',
            component: CarWaitingBusinessPreview,
          },
          {
            id: 'business-car-pickup',
            label: '等待接驾页',
            type: 'item',
            title: '等待接驾页组件预览',
            pathLabel: '业务组件 / 用车 / 等待接驾页',
            description: '这里展示用车等待接驾页拆出来的地图接驾状态、悬浮按钮、司机卡片和客服卡片。',
            statusLabel: '已接入',
            maintenanceHint: '当前挂载的是用车等待接驾页拆分后的业务组件。',
            component: CarPickupBusinessPreview,
          },
          {
            id: 'business-car-send',
            label: '送驾页',
            type: 'item',
            title: '送驾页组件预览',
            pathLabel: '业务组件 / 用车 / 送驾页',
            description: '这里展示用车送驾页拆出来的地图送驾状态、悬浮按钮、司机卡片和客服卡片。',
            statusLabel: '已接入',
            maintenanceHint: '当前挂载的是用车送驾页拆分后的业务组件。',
            component: CarSendBusinessPreview,
          },
          {
            id: 'business-car-payment',
            label: '待支付页',
            type: 'item',
            title: '待支付页组件预览',
            pathLabel: '业务组件 / 用车 / 待支付页',
            description: '这里展示用车待支付页拆出来的路线、支付卡和企业支付确认组件。',
            statusLabel: '已接入',
            maintenanceHint: '当前挂载的是用车待支付页拆分后的业务组件。',
            component: CarPaymentBusinessPreview,
          },
          {
            id: 'business-car-payment-complete',
            label: '支付完成页',
            type: 'item',
            title: '支付完成页组件预览',
            pathLabel: '业务组件 / 用车 / 支付完成页',
            description: '这里展示用车支付完成页拆出来的评价卡、支付完成卡和会员权益组件。',
            statusLabel: '已接入',
            maintenanceHint: '当前挂载的是用车支付完成页拆分后的业务组件。',
            component: CarPaymentCompleteBusinessPreview,
          },
        ],
      },
      {
        id: 'group-business-flight',
        label: '机票',
        hidden: true,
        statusLabel: '已接入',
        type: 'group',
        children: [
          {
            id: 'business-flight-home',
            label: '首页',
            type: 'item',
            title: '首页组件预览',
            pathLabel: '业务组件 / 机票 / 首页',
            description: '这里统一展示机票首页拆出来的业务组件，适合按头图区、填写卡片、保障卡和底部导航持续维护。',
            statusLabel: '已接入',
            maintenanceHint: '当前挂载的是机票首页-因公拆分后的业务组件。',
            component: FlightHomeBusinessPreview,
          },
          {
            id: 'business-flight-list',
            label: '航班列表页',
            type: 'item',
            title: '航班列表页组件预览',
            pathLabel: '业务组件 / 机票 / 航班列表页',
            description: '这里统一展示航班列表页拆出来的业务组件，适合按顶部导航、日期筛选、航班卡片和底部排序栏持续维护。',
            statusLabel: '已接入',
            maintenanceHint: '当前挂载的是航班列表页拆分后的业务组件。',
            component: FlightListBusinessPreview,
          },
          {
            id: 'business-flight-quote',
            label: '航班报价页',
            type: 'item',
            title: '航班报价页组件预览',
            pathLabel: '业务组件 / 机票 / 航班报价页',
            description: '这里统一展示航班报价页拆出来的业务组件，适合按航班概要、舱等切换、筛选标签和报价卡片持续维护。',
            statusLabel: '已接入',
            maintenanceHint: '当前挂载的是航班报价页拆分后的业务组件。',
            component: FlightQuoteBusinessPreview,
          },
          {
            id: 'business-flight-form',
            label: '机票填单页',
            type: 'item',
            title: '机票填单页组件预览',
            pathLabel: '业务组件 / 机票 / 机票填单页',
            description: '这里统一展示机票填单页拆出来的业务组件，适合按导航、提示、费用卡、乘机人、出行服务和提交栏持续维护。',
            statusLabel: '已接入',
            maintenanceHint: '当前挂载的是机票填单页拆分后的业务组件。',
            component: FlightFormBusinessPreview,
          },
          {
            id: 'business-flight-order-detail',
            label: '机票订单详情页',
            type: 'item',
            title: '机票订单详情页组件预览',
            pathLabel: '业务组件 / 机票 / 机票订单详情页',
            description: '这里统一展示机票订单详情页拆出来的业务组件，适合按状态区、支付航班卡、出行信息、增值服务和审批报销信息持续维护。',
            statusLabel: '已接入',
            maintenanceHint: '当前挂载的是机票订单详情页拆分后的业务组件。',
            component: FlightOrderDetailBusinessPreview,
          },
          {
            id: 'business-flight-booking-success',
            label: '机票下单成功页',
            type: 'item',
            title: '机票下单成功页组件预览',
            pathLabel: '业务组件 / 机票 / 机票下单成功页',
            description: '这里展示机票下单成功页里拆出来的成功状态、订单卡片和温馨提示组件，并复用下单成功页同一套组件能力。',
            statusLabel: '已接入',
            maintenanceHint: '当前挂载的是下单成功页通用组件在机票场景下的拆分预览。',
            component: FlightBookingSuccessBusinessPreview,
          },
        ],
      },
    ],
  },
  {
    id: 'group-pages',
    label: '页面案例',
    type: 'group',
    children: [
      {
        id: 'group-pages-hotel',
        label: '酒店',
        type: 'group',
        statusLabel: '已接入',
        children: [
          {
            id: 'page-hotel-home-business',
            label: '酒店首页-因公',
            type: 'item',
            title: '酒店首页-因公整页案例',
            pathLabel: '页面案例 / 酒店 / 酒店首页-因公',
            description: '这里展示酒店首页-因公整页组装后的最终效果，适合从页面层级核对头图、填写卡片和底部权益入口的整体编排。',
            statusLabel: '已接入',
            maintenanceHint: '当前挂载的是酒店首页-因公完整预览。',
            component: HotelHomeBusinessCasePreview,
          },
          {
            id: 'page-hotel-list',
            label: '酒店列表页',
            type: 'item',
            title: '酒店列表页整页案例',
            pathLabel: '页面案例 / 酒店 / 酒店列表页',
            description: '这里展示酒店列表页整页组装后的最终效果，适合从页面层级验证搜索、筛选和列表信息的整体编排。',
            statusLabel: '已接入',
            maintenanceHint: '当前挂载的是酒店列表页完整预览。',
            component: HotelListCasePreview,
          },
          {
            id: 'page-hotel-detail',
            label: '酒店详情页',
            type: 'item',
            title: '酒店详情页整页案例',
            pathLabel: '页面案例 / 酒店 / 酒店详情页',
            description: '这里展示酒店详情页整页组装后的最终效果，适合从页面层级验证头图、房型和酒店基础信息的整体编排。',
            statusLabel: '已接入',
            maintenanceHint: '当前挂载的是酒店详情页完整预览。',
            component: HotelDetailCasePreview,
          },
          {
            id: 'page-hotel-room-detail',
            label: '房型详情页',
            type: 'item',
            title: '房型详情页整页案例',
            pathLabel: '页面案例 / 酒店 / 房型详情页',
            description: '这里展示房型详情页整页组装后的最终效果，适合从页面层面验证完整输出。',
            statusLabel: '已接入',
            maintenanceHint: '当前挂载的是房型详情页完整预览。',
            component: HotelRoomDetailCasePreview,
          },
          {
            id: 'page-hotel-form',
            label: '酒店填单页',
            type: 'item',
            title: '酒店填单页整页案例',
            pathLabel: '页面案例 / 酒店 / 酒店填单页',
            description: '这里展示酒店填单页整页组装后的最终效果，适合从页面层级验证完整输出。',
            statusLabel: '已接入',
            maintenanceHint: '当前挂载的是酒店填单页完整预览。',
            component: HotelFormCasePreview,
          },
          {
            id: 'page-hotel-booking-success',
            label: '酒店下单成功页',
            type: 'item',
            title: '酒店下单成功页整页案例',
            pathLabel: '页面案例 / 酒店 / 酒店下单成功页',
            description: '这里展示酒店下单成功页整页组装后的最终效果，适合从页面层级核对状态文案、订单信息和联订福利推荐的整体编排。',
            statusLabel: '已接入',
            maintenanceHint: '当前挂载的是酒店下单成功页完整预览。',
            component: HotelBookingSuccessCasePreview,
          },
          {
            id: 'page-hotel-order-detail',
            label: '酒店订单详情页',
            type: 'item',
            title: '酒店订单详情页整页案例',
            pathLabel: '页面案例 / 酒店 / 酒店订单详情页',
            description: '这里展示酒店订单详情页整页组装后的最终效果，适合从页面层级核对状态操作、订单信息和权益模块的整体编排。',
            statusLabel: '已接入',
            maintenanceHint: '当前挂载的是酒店订单详情页完整预览。',
            component: HotelOrderDetailCasePreview,
          },
        ],
      },
      {
        id: 'group-pages-car',
        label: '用车',
        statusLabel: '已接入',
        type: 'group',
        children: [
          {
            id: 'page-car-home-default',
            label: '首页',
            type: 'item',
            title: '首页整页案例',
            pathLabel: '页面案例 / 用车 / 首页',
            description: '这里统一展示用车首页整页案例，并在同一预览里区分默认态和全态两个页面状态。',
            statusLabel: '已接入',
            maintenanceHint: '当前挂载的是用车首页默认态与全态的整页预览。',
            component: CarHomeDefaultCasePreview,
          },
          {
            id: 'page-car-location-input',
            label: '起终点输入页',
            type: 'item',
            title: '起终点输入页整页案例',
            pathLabel: '页面案例 / 用车 / 起终点输入页',
            description: '这里展示用车起终点输入页整页组装后的最终效果，适合从页面层级核对地图、上车点和底部输入卡片的整体编排。',
            statusLabel: '已接入',
            maintenanceHint: '当前挂载的是用车起终点输入页完整预览。',
            component: CarLocationInputCasePreview,
          },
          {
            id: 'page-car-bubble',
            label: '冒泡页',
            type: 'item',
            title: '冒泡页整页案例',
            pathLabel: '页面案例 / 用车 / 冒泡页',
            description: '这里展示用车冒泡页整页组装后的最终效果，适合从页面层级核对地图、车型列表和吸底呼叫区。',
            statusLabel: '已接入',
            maintenanceHint: '当前挂载的是用车冒泡页完整预览。',
            component: CarBubbleCasePreview,
          },
          {
            id: 'page-car-waiting',
            label: '等待应答页',
            type: 'item',
            title: '等待应答页整页案例',
            pathLabel: '页面案例 / 用车 / 等待应答页',
            description: '这里展示用车等待应答页整页组装后的最终效果，适合核对寻找司机、加速权益和追加车型流程。',
            statusLabel: '已接入',
            maintenanceHint: '当前挂载的是用车等待应答页完整预览。',
            component: CarWaitingCasePreview,
          },
          {
            id: 'page-car-pickup',
            label: '等待接驾页',
            type: 'item',
            title: '等待接驾页整页案例',
            pathLabel: '页面案例 / 用车 / 等待接驾页',
            description: '这里展示用车等待接驾页整页组装后的最终效果，适合核对地图接驾、司机信息和客服入口。',
            statusLabel: '已接入',
            maintenanceHint: '当前挂载的是用车等待接驾页完整预览。',
            component: CarPickupCasePreview,
          },
          {
            id: 'page-car-send',
            label: '送驾页',
            type: 'item',
            title: '送驾页整页案例',
            pathLabel: '页面案例 / 用车 / 送驾页',
            description: '这里展示用车送驾页整页组装后的最终效果，适合核对地图送驾、司机信息和客服入口。',
            statusLabel: '已接入',
            maintenanceHint: '当前挂载的是用车送驾页完整预览。',
            component: CarSendCasePreview,
          },
          {
            id: 'page-car-payment',
            label: '待支付页',
            type: 'item',
            title: '待支付页整页案例',
            pathLabel: '页面案例 / 用车 / 待支付页',
            description: '这里展示用车待支付页整页组装后的最终效果，适合核对地图路线、费用明细和企业支付确认。',
            statusLabel: '已接入',
            maintenanceHint: '当前挂载的是用车待支付页完整预览。',
            component: CarPaymentCasePreview,
          },
          {
            id: 'page-car-payment-complete',
            label: '支付完成页',
            type: 'item',
            title: '支付完成页整页案例',
            pathLabel: '页面案例 / 用车 / 支付完成页',
            description: '这里展示用车支付完成页整页组装后的最终效果，适合核对评价入口、费用明细和会员权益。',
            statusLabel: '已接入',
            maintenanceHint: '当前挂载的是用车支付完成页完整预览。',
            component: CarPaymentCompleteCasePreview,
          },
        ],
      },
      {
        id: 'group-pages-flight',
        label: '机票',
        statusLabel: '已接入',
        type: 'group',
        children: [
          {
            id: 'page-flight-home',
            label: '机票首页-因公',
            type: 'item',
            title: '机票首页-因公整页案例',
            pathLabel: '页面案例 / 机票 / 机票首页-因公',
            description: '这里展示机票首页-因公整页组装后的最终效果，适合从页面层级核对头图、填写卡片、保障卡和底部导航的整体编排。',
            statusLabel: '已接入',
            maintenanceHint: '当前挂载的是机票首页-因公完整预览。',
            component: FlightHomeCasePreview,
          },
          {
            id: 'page-flight-list',
            label: '航班列表页',
            type: 'item',
            title: '航班列表页整页案例',
            pathLabel: '页面案例 / 机票 / 航班列表页',
            description: '这里展示航班列表页整页组装后的最终效果，适合从页面层级核对顶部筛选、卡片密度和底部排序区的整体编排。',
            statusLabel: '已接入',
            maintenanceHint: '当前挂载的是航班列表页完整预览。',
            component: FlightListCasePreview,
          },
          {
            id: 'page-flight-quote',
            label: '航班报价页',
            type: 'item',
            title: '航班报价页整页案例',
            pathLabel: '页面案例 / 机票 / 航班报价页',
            description: '这里展示航班报价页整页组装后的最终效果，适合从页面层级核对航班概要、舱等切换和多种报价卡片状态。',
            statusLabel: '已接入',
            maintenanceHint: '当前挂载的是航班报价页完整预览。',
            component: FlightQuoteCasePreview,
          },
          {
            id: 'page-flight-form',
            label: '机票填单页',
            type: 'item',
            title: '机票填单页整页案例',
            pathLabel: '页面案例 / 机票 / 机票填单页',
            description: '这里展示机票填单页整页组装后的最终效果，适合从页面层级核对表单模块、出行服务和吸底提交区的整体编排。',
            statusLabel: '已接入',
            maintenanceHint: '当前挂载的是机票填单页完整预览。',
            component: FlightFormCasePreview,
          },
          {
            id: 'page-flight-order-detail',
            label: '机票订单详情页',
            type: 'item',
            title: '机票订单详情页整页案例',
            pathLabel: '页面案例 / 机票 / 机票订单详情页',
            description: '这里展示机票订单详情页整页组装后的最终效果，适合从页面层级核对出票状态、支付航班卡和订单信息的整体编排。',
            statusLabel: '已接入',
            maintenanceHint: '当前挂载的是机票订单详情页完整预览。',
            component: FlightOrderDetailCasePreview,
          },
          {
            id: 'page-flight-booking-success',
            label: '机票下单成功页',
            type: 'item',
            title: '机票下单成功页整页案例',
            pathLabel: '页面案例 / 机票 / 机票下单成功页',
            description: '这里展示机票下单成功页整页组装后的最终效果，适合从页面层级核对等待出票、订单信息和温馨提示的整体编排。',
            statusLabel: '已接入',
            maintenanceHint: '当前挂载的是复用下单成功页通用组件后的机票完整预览。',
            component: FlightBookingSuccessCasePreview,
          },
        ],
      },
      {
        id: 'group-pages-points',
        label: '积分权益',
        statusLabel: '已接入',
        type: 'group',
        children: [
          {
            id: 'page-points-lucky-bag',
            label: '小福包',
            type: 'item',
            title: '小福包整页案例',
            pathLabel: '页面案例 / 积分权益 / 小福包',
            description: '这里展示积分权益业务的小福包整页组装效果，适合核对积分抽券、兑换好礼、赚积分任务和权益模块。',
            statusLabel: '已接入',
            maintenanceHint: '当前挂载的是小福包默认场景长图拆分后的完整预览。',
            component: PointsLuckyBagCasePreview,
          },
          {
            id: 'page-points-earn-tasks',
            label: '做任务赚积分',
            type: 'item',
            title: '做任务赚积分整页案例',
            pathLabel: '页面案例 / 积分权益 / 做任务赚积分',
            description: '这里展示积分权益业务的任务积分页，包含用车阶梯任务、任务列表、省立返积分规则和积分获取示例。',
            statusLabel: '已接入',
            maintenanceHint: '当前挂载的是做任务赚积分的完整长页预览。',
            component: PointsEarnTasksCasePreview,
          },
          {
            id: 'page-points-mall',
            label: '积分商城',
            type: 'item',
            title: '积分商城整页案例',
            pathLabel: '页面案例 / 积分权益 / 积分商城',
            description: '这里展示积分权益业务的积分商城整页组装效果，适合核对顶部积分入口、限时秒杀、特惠专区、任务卡和兑换好礼模块。',
            statusLabel: '已接入',
            maintenanceHint: '当前挂载的是积分商城默认场景长图拆分后的完整预览。',
            component: PointsMallCasePreview,
          },
          {
            id: 'page-points-product-detail-overlay',
            label: '商品详情浮层',
            type: 'item',
            title: '商品详情浮层整页案例',
            pathLabel: '页面案例 / 积分权益 / 商品详情浮层',
            description: '这里展示积分权益业务的商品详情浮层，适合核对商品头图、套餐包含、使用须知、购买规则和底部兑换按钮。',
            statusLabel: '已接入',
            maintenanceHint: '当前挂载的是商品详情浮层完整预览。',
            component: PointsProductDetailOverlayCasePreview,
          },
          {
            id: 'page-points-exchange-success-overlay',
            label: '兑换成功浮层',
            type: 'item',
            title: '兑换成功浮层整页案例',
            pathLabel: '页面案例 / 积分权益 / 兑换成功浮层',
            description: '这里展示积分权益业务的兑换成功浮层，适合核对成功反馈、商品信息卡片和底部双按钮操作区。',
            statusLabel: '已接入',
            maintenanceHint: '当前挂载的是兑换成功浮层完整预览。',
            component: PointsExchangeSuccessOverlayCasePreview,
          },
        ],
      },
      {
        id: 'group-pages-train',
        label: '火车票',
        statusLabel: '待补充',
        type: 'group',
        children: [
          {
            id: 'pages-train-placeholder',
            label: '预留位',
            type: 'item',
            title: '火车票页面案例',
            pathLabel: '页面案例 / 火车票',
            description: '火车票页面案例的目录位已经预留，后续可以继续补整页输出案例。',
            statusLabel: '待补充',
            maintenanceHint: '建议后续放车次页、填单页等完整页面案例。',
            component: createPlaceholderItem({
              badge: '页面案例',
              title: '火车票页面案例预留位',
              summary: '这里用于承接火车票相关完整页面的最终预览效果。',
              nextSteps: [
                '1. 新建火车票页面预览组件',
                '2. 在注册表里绑定到这里',
                '3. 统一按页面案例维护',
              ],
            }),
          },
        ],
      },
    ],
  },
]

export const defaultPreviewId = 'page-hotel-form'

function collectPreviewItems(items, collected = []) {
  items.forEach((item) => {
    if (item.type === 'group') {
      collectPreviewItems(item.children, collected)
      return
    }

    collected.push(item)
  })

  return collected
}

const previewItemMap = new Map(
  collectPreviewItems(previewNavigation).map((item) => [item.id, item]),
)

const previewIdAliases = {
  'business-hotel-home-business': 'business-hotel-components',
  'business-hotel-list': 'business-hotel-components',
  'business-hotel-detail': 'business-hotel-components',
  'business-hotel-room-detail': 'business-hotel-components',
  'business-hotel-form': 'business-hotel-components',
  'business-hotel-booking-success': 'business-hotel-components',
  'business-hotel-order-detail': 'business-hotel-components',
  'business-car-home-default': 'business-car-components',
  'business-car-location-input': 'business-car-components',
  'business-car-bubble': 'business-car-components',
  'business-car-waiting': 'business-car-components',
  'business-car-pickup': 'business-car-components',
  'business-car-send': 'business-car-components',
  'business-car-payment': 'business-car-components',
  'business-car-payment-complete': 'business-car-components',
  'business-flight-home': 'business-flight-components',
  'business-flight-list': 'business-flight-components',
  'business-flight-quote': 'business-flight-components',
  'business-flight-form': 'business-flight-components',
  'business-flight-order-detail': 'business-flight-components',
  'business-flight-booking-success': 'business-flight-components',
}

export function resolvePreviewId(id) {
  if (previewIdAliases[id]) {
    return previewIdAliases[id]
  }

  const generatedBusinessComponentId = /^business-(hotel|car|flight|points)-.+-\d+$/.exec(id)

  if (generatedBusinessComponentId) {
    return `business-${generatedBusinessComponentId[1]}-components`
  }

  return id
}

export function findPreviewById(id) {
  return previewItemMap.get(id)
}
